export const VALID_SKILLS = ["LESEN", "SCHREIBEN", "HOEREN", "SPRECHEN", "WORTSCHATZ", "GRAMMATIK"] as const;
export const VALID_TYPES = [
  "LESEN_ZUORDNUNG","LESEN_MULTIPLE_CHOICE","LESEN_RICHTIG_FALSCH","LESEN_LUECKENTEXT","LESEN_REIHENFOLGE",
  "SCHREIBEN_EMAIL","SCHREIBEN_NOTIZ","SCHREIBEN_MEINUNG","SCHREIBEN_BESCHREIBUNG","SCHREIBEN_ZUSAMMENFASSUNG",
  "HOEREN_MULTIPLE_CHOICE","HOEREN_ZUORDNUNG","HOEREN_ERGAENZUNG","HOEREN_RICHTIG_FALSCH",
  "SPRECHEN_VORSTELLEN","SPRECHEN_DIALOG","SPRECHEN_BESCHREIBUNG","SPRECHEN_DISKUSSION","SPRECHEN_ROLEPLAY",
  "VOCAB_FLASHCARD","VOCAB_LUECKENTEXT","VOCAB_ZUORDNUNG","VOCAB_BILD","VOCAB_SEKTOR",
  "GRAMMATIK_LUECKENTEXT","GRAMMATIK_ORDNEN","GRAMMATIK_TRANSFORMATION","GRAMMATIK_FEHLERKORREKTUR",
] as const;

const TYPE_ALIASES: Record<string, string> = {
  "MATCHING_HEADLINES":"LESEN_ZUORDNUNG","HEADLINE_MATCHING":"LESEN_ZUORDNUNG",
  "SITUATION_AD_MATCHING":"LESEN_ZUORDNUNG","AD_MATCHING":"LESEN_ZUORDNUNG",
  "TEXT_MATCHING":"LESEN_ZUORDNUNG","ZUORDNUNG":"LESEN_ZUORDNUNG",
  "MULTIPLE_CHOICE_READING":"LESEN_MULTIPLE_CHOICE","READING_COMPREHENSION":"LESEN_MULTIPLE_CHOICE",
  "LESEVERSTEHEN":"LESEN_MULTIPLE_CHOICE","LESEN_VERSTAENDNIS":"LESEN_MULTIPLE_CHOICE",
  "TRUE_FALSE":"LESEN_RICHTIG_FALSCH","RICHTIG_FALSCH":"LESEN_RICHTIG_FALSCH",
  "GAP_FILL":"LESEN_LUECKENTEXT","LUECKENTEXT":"LESEN_LUECKENTEXT","FILL_IN_THE_BLANK":"LESEN_LUECKENTEXT",
  "ORDERING":"LESEN_REIHENFOLGE","REIHENFOLGE":"LESEN_REIHENFOLGE",
  "EMAIL_WRITING":"SCHREIBEN_EMAIL","LETTER_WRITING":"SCHREIBEN_EMAIL","BRIEF":"SCHREIBEN_EMAIL",
  "OPINION_WRITING":"SCHREIBEN_MEINUNG","MEINUNGSAEUSSERUNG":"SCHREIBEN_MEINUNG",
  "DESCRIPTION":"SCHREIBEN_BESCHREIBUNG","BILDBESCHREIBUNG":"SCHREIBEN_BESCHREIBUNG",
  "SUMMARY":"SCHREIBEN_ZUSAMMENFASSUNG","ZUSAMMENFASSUNG":"SCHREIBEN_ZUSAMMENFASSUNG",
  "MULTIPLE_CHOICE_LISTENING":"HOEREN_MULTIPLE_CHOICE","LISTENING_COMPREHENSION":"HOEREN_MULTIPLE_CHOICE",
  "HOERVERSTEHEN":"HOEREN_MULTIPLE_CHOICE","LISTENING_MATCHING":"HOEREN_ZUORDNUNG",
  "LISTENING_GAP_FILL":"HOEREN_ERGAENZUNG","LISTENING_TRUE_FALSE":"HOEREN_RICHTIG_FALSCH",
  "DIALOG":"SPRECHEN_DIALOG","ROLEPLAY":"SPRECHEN_ROLEPLAY","ROLE_PLAY":"SPRECHEN_ROLEPLAY",
  "PRESENTATION":"SPRECHEN_VORSTELLEN","DISCUSSION":"SPRECHEN_DISKUSSION",
  "FLASHCARD":"VOCAB_FLASHCARD","VOCABULARY":"VOCAB_FLASHCARD","VOKABULAR":"VOCAB_FLASHCARD","VOCAB":"VOCAB_FLASHCARD",
  "VOCABULARY_MATCHING":"VOCAB_ZUORDNUNG","WORD_MATCHING":"VOCAB_ZUORDNUNG",
  "VOCABULARY_GAP":"VOCAB_LUECKENTEXT","VOCABULARY_FILL":"VOCAB_LUECKENTEXT",
  "PICTURE_VOCABULARY":"VOCAB_BILD","SECTOR_VOCABULARY":"VOCAB_SEKTOR",
  "GRAMMAR_GAP":"GRAMMATIK_LUECKENTEXT","GRAMMAR_FILL":"GRAMMATIK_LUECKENTEXT","GRAMMAR":"GRAMMATIK_LUECKENTEXT",
  "SENTENCE_BUILDING":"GRAMMATIK_ORDNEN","WORD_ORDER":"GRAMMATIK_ORDNEN",
  "TRANSFORMATION":"GRAMMATIK_TRANSFORMATION",
  "ERROR_CORRECTION":"GRAMMATIK_FEHLERKORREKTUR","FEHLERKORREKTUR":"GRAMMATIK_FEHLERKORREKTUR",
};

export function normalizeSkill(raw: string | undefined): typeof VALID_SKILLS[number] {
  const upper = (raw ?? "").toUpperCase();
  if ((VALID_SKILLS as readonly string[]).includes(upper)) return upper as typeof VALID_SKILLS[number];
  if (upper.startsWith("LESEN")) return "LESEN";
  if (upper.startsWith("SCHREIBEN")) return "SCHREIBEN";
  if (upper.startsWith("HOEREN") || upper.includes("LISTEN")) return "HOEREN";
  if (upper.startsWith("SPRECHEN") || upper.includes("SPEAK") || upper.includes("DIALOG")) return "SPRECHEN";
  if (upper.startsWith("VOCAB") || upper.includes("VOCABULARY") || upper.includes("VOKAB")) return "WORTSCHATZ";
  if (upper.startsWith("GRAMMATIK") || upper.includes("GRAMMAR")) return "GRAMMATIK";
  return "WORTSCHATZ";
}

export function normalizeType(raw: string | undefined): typeof VALID_TYPES[number] {
  const upper = (raw ?? "").toUpperCase().replace(/-/g, "_").replace(/\s+/g, "_");
  if ((VALID_TYPES as readonly string[]).includes(upper)) return upper as typeof VALID_TYPES[number];
  if (TYPE_ALIASES[upper]) return TYPE_ALIASES[upper] as typeof VALID_TYPES[number];
  for (const [alias, target] of Object.entries(TYPE_ALIASES)) {
    if (upper.includes(alias) || alias.includes(upper)) return target as typeof VALID_TYPES[number];
  }
  if (upper.startsWith("LESEN") || upper.includes("READING")) return "LESEN_MULTIPLE_CHOICE";
  if (upper.startsWith("SCHREIBEN") || upper.includes("WRITING")) return "SCHREIBEN_EMAIL";
  if (upper.startsWith("HOEREN") || upper.includes("LISTEN")) return "HOEREN_MULTIPLE_CHOICE";
  if (upper.startsWith("SPRECHEN") || upper.includes("SPEAK")) return "SPRECHEN_DIALOG";
  if (upper.startsWith("VOCAB") || upper.includes("VOCABULARY")) return "VOCAB_FLASHCARD";
  if (upper.startsWith("GRAMMATIK") || upper.includes("GRAMMAR")) return "GRAMMATIK_LUECKENTEXT";
  return "LESEN_MULTIPLE_CHOICE";
}
